<a href="https://colab.research.google.com/github/pavanreddy565/NLP_Telugu_Resources/blob/main/Tokenization%20/Telugu_Tokenization_using_nltk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html


Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.3.1+cpu (from versions: 1.11.0, 1.11.0+cpu, 1.12.0, 1.12.0+cpu, 1.12.1, 1.12.1+cpu, 1.13.0, 1.13.0+cpu, 1.13.1, 1.13.1+cpu, 2.0.0, 2.0.0+cpu, 2.0.1, 2.0.1+cpu, 2.1.0, 2.1.0+cpu, 2.1.1, 2.1.1+cpu, 2.1.2, 2.1.2+cpu, 2.2.0, 2.2.0+cpu, 2.2.1, 2.2.1+cpu, 2.2.2, 2.2.2+cpu, 2.3.0, 2.3.0+cpu, 2.3.1, 2.3.1+cpu)
ERROR: No matching distribution found for torch==1.3.1+cpu


In [12]:
!pip install torch==2.3.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html


Looking in links: https://download.pytorch.org/whl/cpu/torch_stable.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.4/190.4 MB 3.3 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 2.3.1+cu121
    Uninstalling torch-2.3.1+cu121:
      Successfully uninstalled torch-2.3.1+cu121


In [13]:
!pip install inltk

In [16]:
!pip install nest_asyncio


In [20]:
import nest_asyncio
import collections
import asyncio
from concurrent.futures import ThreadPoolExecutor

# Apply the nest_asyncio to allow nesting of event loops
nest_asyncio.apply()

# Patch for inltk to work with Python 3.10
if not hasattr(collections, 'Iterable'):
    import collections.abc
    collections.Iterable = collections.abc.Iterable

# Import inltk and the setup function
from inltk.inltk import setup

# Define a function to run setup in a separate thread
def run_setup():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    setup('te')

# Use ThreadPoolExecutor to run the setup function in a separate thread
executor = ThreadPoolExecutor(max_workers=1)
executor.submit(run_setup).result()

# Close the executor
executor.shutdown()


We'll only do this for the first time.
We'll only do this for the first time.
Done!


In [26]:
from inltk.inltk import tokenize

telugu_text = """ ఏళ్ళ వయస్సులో గద్దె నెక్కాడు. తన పాలనాకాలంలో ఎక్కువ భాగం పశ్చిమ ఆసియా, ఈశాన్య ఆఫ్రికాల్లో మున్నెన్నడూ ఎరగని సైనిక దండయాత్ర లోనే గడిపాడు. ముప్పై సంవత్సరాల వయస్సు నాటికే, గ్రీస్ నుండి వాయవ్య భారతదేశం వరకు విస్తరించిన, పురాతన ప్రపంచంలోని అతిపెద్ద సామ్రాజ్యాలలో ఒకదాన్ని సృష్టించాడు. అతను యుద్ధంలో అజేయంగా నిలిచాడు. చరిత్రలో అత్యంత విజయవంతమైన సేనాధిపతుల్లో ఒకరిగా అతన్ని పరిగణిస్తారు. అలెగ్జాండర్‌ 16 సంవత్సరాల వయస్సు వచ్చే వరకు అరిస్టాటిల్ వద్ద విద్య అభ్యసించాడు. సా.పూ 336 లో ఫిలిప్ హత్య తరువాత, అతను సింహాసనం ఎక్కాడు. బలమైన రాజ్యాన్ని, అనుభవంగల సైన్యాన్నీ వారసత్వంగా పొందాడు. అలెగ్జాండర్‌కు గ్రీస్ సర్వసైన్యాధిపత్యం లభించింది. తన తండ్రి తలపెట్టి, మొదలుపెట్టలేక పోయిన పాన్-హెలెనిక్ ప్రాజెక్టును ప్రారంభించి, పర్షియాను ఆక్రమించడానికి ఈ అధికారాన్ని ఉపయోగించాడు."""

# tokenize(input text, language code)
tokenize(hindi_text, "te")

['▁ఏళ్ళ',
 '▁వయస్సులో',
 '▁గద్దె',
 '▁నె',
 'క్క',
 'ాడు',
 '.',
 '▁తన',
 '▁పాలనా',
 'కాలంలో',
 '▁ఎక్కువ',
 '▁భాగం',
 '▁పశ్చిమ',
 '▁ఆసియా',
 ',',
 '▁ఈశాన్య',
 '▁ఆఫ్రికా',
 'ల్లో',
 '▁ము',
 'న్నె',
 'న్న',
 'డూ',
 '▁ఎ',
 'రగ',
 'ని',
 '▁సైనిక',
 '▁దండయాత్ర',
 '▁లోనే',
 '▁గడిపాడు',
 '.',
 '▁ముప్పై',
 '▁సంవత్సరాల',
 '▁వయస్సు',
 '▁నాటికే',
 ',',
 '▁గ్రీస్',
 '▁నుండి',
 '▁వాయవ్య',
 '▁భారతదేశం',
 '▁వరకు',
 '▁విస్తరించిన',
 ',',
 '▁పురాతన',
 '▁ప్రపంచంలోని',
 '▁అతిపెద్ద',
 '▁సామ్రాజ్యాల',
 'లో',
 '▁ఒక',
 'దాన్ని',
 '▁సృష్టించాడు',
 '.',
 '▁అతను',
 '▁యుద్ధంలో',
 '▁అ',
 'జేయ',
 'ంగా',
 '▁నిలిచాడు',
 '.',
 '▁చరిత్రలో',
 '▁అత్యంత',
 '▁విజయవంతమైన',
 '▁సేన',
 'ాధిపతుల',
 '్లో',
 '▁ఒకరిగా',
 '▁అతన్ని',
 '▁పరిగణిస్తారు',
 '.',
 '▁అలెగ్జాండర్',
 '▁16',
 '▁సంవత్సరాల',
 '▁వయస్సు',
 '▁వచ్చే',
 '▁వరకు',
 '▁అరిస్టాటిల్',
 '▁వద్ద',
 '▁విద్య',
 '▁అభ్యసించాడు',
 '.',
 '▁సా',
 '.',
 'పూ',
 '▁3',
 '36',
 '▁లో',
 '▁ఫిలిప్',
 '▁హత్య',
 '▁తరువాత',
 ',',
 '▁అతను',
 '▁సింహాసనం',
 '▁ఎక్క',
 'ాడు',
 '.',
 '▁బలమైన',
 '▁

In [24]:
import nest_asyncio
import collections
import asyncio
from concurrent.futures import ThreadPoolExecutor

# Apply the nest_asyncio to allow nesting of event loops
nest_asyncio.apply()

# Patch for inltk to work with Python 3.10
if not hasattr(collections, 'Iterable'):
    import collections.abc
    collections.Iterable = collections.abc.Iterable

# Import inltk and the setup function
from inltk.inltk import setup

# Define a function to run setup in a separate thread
def run_setup(lang):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    setup(lang)

# Use ThreadPoolExecutor to run the setup function in a separate thread for Hindi and Telugu
executor = ThreadPoolExecutor(max_workers=2)
executor.submit(run_setup, 'te').result()
executor.submit(run_setup, 'te').result()

# Close the executor
executor.shutdown()


Done!
Done!


In [29]:
import nest_asyncio
import collections
import asyncio
from concurrent.futures import ThreadPoolExecutor

# Apply nest_asyncio to allow nesting of event loops
nest_asyncio.apply()

# Patch for inltk to work with Python 3.10
if not hasattr(collections, 'Sized'):
    import collections.abc
    collections.Sized = collections.abc.Sized

# Import inltk and the setup function
from inltk.inltk import setup

# Define a function to run setup in a separate thread
def run_setup(lang):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    setup(lang)

# Use ThreadPoolExecutor to run the setup function in a separate thread for Telugu
executor = ThreadPoolExecutor(max_workers=1)
executor.submit(run_setup, 'te').result()

# Close the executor
executor.shutdown()


Done!


In [30]:
from inltk.inltk import get_embedding_vectors

vectors = get_embedding_vectors(telugu_text, 'te')

In [31]:
vectors

[array([ 0.118539, -0.231999, -0.113829, -0.082277, ..., -0.046054,  0.147202, -0.098554,  0.082662], dtype=float32),
 array([ 0.016471, -0.099307,  0.119358,  0.00501 , ..., -0.003194,  0.086803,  0.101685, -0.036668], dtype=float32),
 array([-0.020547, -0.077961, -0.131776,  0.089729, ..., -0.055219, -0.020255, -0.021535, -0.013551], dtype=float32),
 array([ 0.066331,  0.034478,  0.064582,  0.027809, ...,  0.011288, -0.075349, -0.017159, -0.036531], dtype=float32),
 array([ 0.107894, -0.205356,  0.039795,  0.067916, ..., -0.049686, -0.044448, -0.095413, -0.017411], dtype=float32),
 array([ 0.144239, -0.055852,  0.215159,  0.318129, ..., -0.013692,  0.119321, -0.212985,  0.059699], dtype=float32),
 array([ 0.242197,  0.227901,  0.124662, -0.27727 , ...,  0.314803, -0.17433 ,  0.278329,  0.182786], dtype=float32),
 array([ 0.287298,  0.051568,  0.043172,  0.115851, ...,  0.148276, -0.128211,  0.107505,  0.103582], dtype=float32),
 array([ 0.00424 ,  0.002706,  0.098056, -0.038045, ...,